// Generated by scripts/recovery/generate-shims.mjs. A compat shim is correct when every old name IS the owner's export.
import test from "node:test";
import assert from "node:assert/strict";
import * as shim0 from "../dist/index.js";
import * as owner0 from "obix-core-func";

test("obix-binding-func: every old name is the owner's export, and nothing else is exported", () => {
  assert.equal(shim0["toFunctional"], owner0["toFunctional"], "toFunctional");
  assert.deepEqual(Object.keys(shim0).sort(), ["toFunctional"]);
});
