// Generated by scripts/recovery/generate-shims.mjs — a compat shim: no logic, only the owner's exports under the old names.
export { toFunctional } from "obix-core-func";
export type { FunctionalInstance, FunctionalProjection } from "obix-core-func";
